# Generated by Django 4.2 on 2023-04-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allusers',
            old_name='usename',
            new_name='username',
        ),
    ]
