# Generated by Django 4.2 on 2023-04-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_rename_usename_allusers_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allusers',
            new_name='All',
        ),
    ]
