# Generated by Django 4.2 on 2023-04-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_rename_allusers_all'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All',
            new_name='Userss',
        ),
    ]
