# Generated by Django 4.2 on 2023-04-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_rename_all_userss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userss',
            new_name='UsersTable',
        ),
    ]
